included:
  - Package.swift
  - Sources
  - Tests
  - scripts

excluded:
  - .build
  - .dist
  - .release
  - .xcode-dd
  - OpenSnek.xcodeproj

disabled_rules:
  - function_body_length
  - cyclomatic_complexity
  - type_body_length
  - line_length
  - identifier_name

file_length:
  warning: 1200
  error: 1800

strict: true
